book/urls.py
from django.urls import path
from . import views

app_name = 'book'
urlpatterns = [
    path('booking/', views.BookingView.as_view(), name='booking'),
    path('manage_book/', views.ManageBookView.as_view(), name='manage_book'),
    path('add_info/', views.AddInfoView.as_view(), name='add_info'),
]

car/urls.py
from django.urls import path
from . import views

app_name = 'car'
urlpatterns = [
    path('manage_car/', views.ManageCarView.as_view(), name='manage_car'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# mediaから画像を読み込む用
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('order.urls')),
    path('users/', include('users.urls')),
    path('book/', include('book.urls')),
    path('car/', include('car.urls')),
]

# mediaから画像を読み込む用
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('sign_up/', views.SignUpView.as_view(template_name='users/sign_up.html'), name='sign_up'),
    path('create_group/', views.CreateGroupView.as_view(), name='create_group'),
    path('manage_and_search_group/', views.ManageAndSearchGroupView.as_view(), name='manage_and_search_group'),
    path('manage_group/<str:group_name>', views.ManageGroupView.as_view(), name='manage_group'),
]

templates/common/base.html
{% load static %}
<!DOCTYPE html>
<html lang="jp">
<head>
	<title>CARM</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="{% static 'common/images/icons/favicon.ico' %}"/>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'common/css/reset.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'common/css/font-awesome-5.15.1/css/all.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'common/css/header_style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'common/css/users_style.css' %}" type="text/css">

    {% block style %}
    {% endblock %}

</head>
<body>
	
    <!-- Header Start -->
    <header class="site__header">
        <div class="wrapper site__header__wrapper">
            <div class="site__header__start">
                <a href="{% url 'order:home'%}"><img src="{% static 'common/images/logo_mini_alfha_white.png'%}" height="30px"></a>
            </div>
            <div class="site__header__end">
                <label class="user__info__toggle">{% if user.is_authenticated %}<img class="user__image" src="{{user.user_image.url}}">{% else %}<img class="user__image" src="{% static 'common/images/default_user.jpeg'%}">{% endif %}</label>
            </div>
        </div>
    </header>

    <div class="user__info hidden__user__info">
        <div class="user__info__toggle user__info__item"><i class="fas fa-times-circle"></i>&nbsp&nbspユーザメニューを閉じる</div>
        <hr>
        <div class="user__info__item"><i class="fas fa-user"></i>&nbsp&nbsp{% if user.is_authenticated %}{{user.username}}{% else %}Guest{% endif %}</div>
        {% if user.is_authenticated %}<div class="user__info__item"><i class="fas fa-envelope"></i>&nbsp&nbsp{{user.email}}</div>{% endif %}
        <div class="user__info__item"><i class="fas fa-users"></i>&nbsp&nbsp{% if user.is_authenticated and user.active_group is not None %}{{user.active_group}}{% else %}independent{% endif %}</div>
        <hr>
        <a class="user__info__item" href="{% url 'order:home'%}"><i class="fas fa-home"></i>&nbsp&nbspホーム</a><br>
        {% if user.is_superuser %}<a class="user__info__item" href="{% url 'admin:index'%}"><i class="fas fa-crown"></i>&nbsp&nbsp管理画面</a><br>{% endif %}
        {% if user.is_authenticated %}
        Group：
        <a class="user__info__item" href="{% url 'users:create_group'%}">作成</a>｜
        <a class="user__info__item" href="{% url 'users:manage_and_search_group'%}">管理・検索</a><br>
        Book：
        <a class="user__info__item" href="{% url 'book:manage_book' %}">管理・日報</a><br>
        {% endif %}
        {% if user == user.active_group.leader %}
        Car：
        <a class="user__info__item" href="{% url 'car:manage_car' %}">管理</a>
        {% endif %}
        <hr>
        {% if user.is_authenticated %}
            <a class="user__info__item" href="{% url 'users:logout'%}"><i class="fas fa-sign-out-alt"></i>&nbsp&nbspログアウト</a>
        {% else %}
            <a class="user__info__item" href="{% url 'users:login'%}"><i class="fas fa-sign-in-alt"></i>&nbsp&nbspログイン</a>
        {% endif %}
    </div>

    <!-- <button class="car__item__trigger" data-filter="all">ALL</button>
    <button class="car__item__trigger" data-filter=".bus">bus</button>
    <button class="car__item__trigger" data-filter=".passenger">passenger</button>
    <button class="car__item__trigger" data-filter=".special">special</button>

    <div class="car__item_list">
        <div class="mix filter bus">bus1</div>
        <div class="mix filter bus">bus2</div>
        <div class="mix filter bus">bus3</div>
        <div class="mix filter bus">bus4</div>
        <div class="mix filter passenger">passenger1</div>
        <div class="mix filter passenger">passenger2</div>
        <div class="mix filter special">special1</div>
        <div class="mix filter special">special2</div>
        <div class="mix filter special">special3</div>
        <div class="mix filter special">special4</div>

    </div>

    <form method="post" class="validate__form">{% csrf_token %}
        <input type="datetime" name="start_date" class="validate__date__input"/>
        <input type="datetime" name="end_date" class="validate__date__input"/>
        <input type="submit" value="送信">
    </form>
 -->


    <!-- Header End -->

    {% block content %}
    {% endblock %}


	<script src="{% static 'common/js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'common/js/mixitup/mixitup.js' %}"></script>
    <script src="{% static 'common/js/header.js' %}"></script>
    
    {% block script %}
    {% endblock %}

</body>
</html>