car/urls.py
from django.urls import path
from . import views

app_name = 'car'
urlpatterns = [
    path('manage_car/', views.ManageCarView.as_view(), name='manage_car'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# mediaから画像を読み込む用
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('order.urls')),
    path('users/', include('users.urls')),
    path('book/', include('book.urls')),
    path('car/', include('car.urls')),
]

# mediaから画像を読み込む用
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('sign_up/', views.SignUpView.as_view(template_name='users/sign_up.html'), name='sign_up'),
    path('create_group/', views.CreateGroupView.as_view(), name='create_group'),
    path('manage_and_search_group/', views.ManageAndSearchGroupView.as_view(), name='manage_and_search_group'),
    path('manage_group/<str:group_name>', views.ManageGroupView.as_view(), name='manage_group'),
]

users/models.py
from django.apps import apps
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.validators import UnicodeUsernameValidator


class UserManager(BaseUserManager):
    """カスタムユーザーマネージャーモデル"""
    use_in_migrations = True

    def _create_user(self, username, email, password, **extra_fields):
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, password, **extra_fields)

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(username, email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル"""
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=30,
        help_text=_('Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
    )
    email = models.EmailField(_('email address'), unique=True)
    #フォロイーフィールドをUser自身に持たせる
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    user_image = models.ImageField(upload_to='images/users', default="images/users/default_user.jpeg")
    active_group = models.ForeignKey('UserGroup', on_delete=models.SET_NULL, null=True, related_name='active_group')

    objects = UserManager()

    USERNAME_FIELD = "email"
    EMAIL_FIELD = "email"
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')


class UserGroup(models.Model):
    name = models.CharField(
        _('name'),
        max_length=15,
        help_text=_('Required. 15 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        unique=True,
    )
    leader = models.ForeignKey(User, on_delete=models.CASCADE, related_name='leader')
    members = models.ManyToManyField(User, blank=True, related_name='members') # 承認済みメンバー
    unapproved_members = models.ManyToManyField(User, blank=True, related_name='unapproved_members') # 未承認メンバー

    class Meta:
        verbose_name = _('user_group')

    def __str__(self):
        return self.name

users/forms.py
from django import forms
from .models import User, UserGroup
from django.contrib.auth import password_validation
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.hashers import make_password

class UserCreationForm(forms.Form):
    username = forms.CharField(
        label=_('username'),
        max_length=30,
        widget=forms.TextInput(attrs={
            'placeholder': 'username',
        }),
        help_text=_('Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'),
    )
    email = forms.EmailField(
        label=_('email address'),
        widget=forms.EmailInput(attrs={
            'autocomplete': 'email',
            'placeholder': 'email'
        })
    )
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'placeholder': 'password',
        }),
        help_text=password_validation.password_validators_help_text_html(),
    )

    class Meta:
        model = User
        fields = ("username", 'email')

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            self.add_error('email', '既に登録済みのメールアドレスです')
        self.cleaned_data['password1'] = make_password(self.cleaned_data['password1'])
        return self.cleaned_data

    def save(self):
        data = self.cleaned_data
        usergroup = UserGroup.objects.get(name="independent")
        new_user = User.objects.create(username=data['username'], email=data['email'], password=data['password1'], active_group=usergroup)
        new_user.save()
        usergroup.members.add(new_user)
        usergroup.save()
        return new_user
        
        
class GroupCreationForm(forms.Form):
    groupname = forms.CharField(
        label=_('groupname'),
        max_length=15,
        widget=forms.TextInput(attrs={
            'placeholder': 'group name',
        }),
        help_text=_('Required. 15 characters or fewer. Letters, digits and @/./+/-/_ only.'),
    )
    
    class Meta:
        model = UserGroup
        fields = ['groupname']

    def clean(self):
        groupname = self.cleaned_data.get('groupname')
        if UserGroup.objects.filter(name=groupname).exists():
            self.add_error('groupname', '既に使われているのグループ名です')
        return self.cleaned_data

    def save(self, user=None):
        groupname = self.cleaned_data.get('groupname')
        new_usergroup = UserGroup.objects.create(name=groupname, leader=user)
        new_usergroup.members.add(user)
        new_usergroup.save()
        return new_usergroup

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from .forms import UserCreationForm, GroupCreationForm
from django.contrib.auth import login
from .models import User, UserGroup
from common.view_utils import common_process

class SignUpView(TemplateView):
    template_name = "users/sign_up.html"

    def get(self, request):
        return render(request, self.template_name, {
            "form": UserCreationForm(),
        })

    def post(self, request, **kwargs):
        if self.request.POST['action'] == 'sign_up':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user)
                return redirect('order:home') # 本当はhomeへ遷移
            else:
                return render(request, self.template_name, {'form': form})


class CreateGroupView(TemplateView):
    template_name = "users/create_group.html"

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        return render(request, self.template_name, {
            "form": GroupCreationForm(),
        })

    def post(self, request, **kwargs):
        if self.request.POST['action'] == 'create_group':
            form = GroupCreationForm(request.POST)
            if form.is_valid():
                group = form.save(user=request.user)
                request.user.active_group = group
                request.user.save()
                return redirect('order:home')
            else:
                return render(request, self.template_name, {'form': form})


class ChangeGroupView(TemplateView):
    template_name = "users/change_group.html"

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        return render(request, self.template_name, {
            "groups": UserGroup.objects.filter(leader=request.user),
        })

    def post(self, request, **kwargs):
        if self.request.POST['action'] == 'change_group':
            pass


class ManageAndSearchGroupView(TemplateView):
    template_name = "users/manage_and_search_group.html"

    session_keys = [("searched_group_name", None)] # (post_key, default_obj)

    def get(self, request):
        if not request.user.is_authenticated:
            return redirect('users:login')
        session_info = {k: request.session[k] if k in request.session.keys() else default_v for k, default_v in self.session_keys}
        searched_group_name = session_info['searched_group_name']
        member_status = "not_application"
        if searched_group_name is not None:
            try:
                group = UserGroup.objects.get(name=searched_group_name)
                if request.user in group.unapproved_members.all():
                    # print("未承認メンバーに所属")
                    member_status = "unapproved"
                elif request.user in group.members.all():
                    # print("承認済みメンバーに所属")
                    member_status = "approved"
            except:
                pass
        return render(request, self.template_name, {
            "searched_group_name": searched_group_name,
            "member_status": member_status,
            "belong_groups": request.user.members.all(), # related_nameを用いた逆参照 # https://hamaguchictrlz.hatenablog.com/entry/2019/02/10/221143
        })

    def post(self, request, **kwargs):
        if 'action' in self.request.POST.keys():
            if self.request.POST['action'] == 'search_group':
                searched_group_name = self.request.POST['searched_group_name']
                try:
                    group = UserGroup.objects.get(name=searched_group_name)
                    request.session['searched_group_name'] = group.name
                except:
                    request.session['searched_group_name'] = None
            elif self.request.POST['action'] == 'application':
                search_result = self.request.POST['search_result']
                try:
                    # print("承認申請")
                    group = UserGroup.objects.get(name=search_result)
                    group.unapproved_members.add(request.user)
                    group.save()
                except:
                    pass
            elif self.request.POST['action'] == 'activation':
                group_name = self.request.POST['group_name']
                group = UserGroup.objects.get(name=group_name)
                user = User.objects.get(pk=request.user.pk)
                user.active_group = group
                user.save()
                
        return redirect('users:manage_and_search_group')


class ManageGroupView(TemplateView):
    template_name = "users/manage_group.html"

    session_keys = [] # (post_key, default_obj)

    def get(self, request, **kwargs):
        if not request.user.is_authenticated:
            return redirect('users:login')
        
        group_name = self.kwargs.get('group_name')
        group = UserGroup.objects.get(name=group_name)

        if group.leader != request.user: # グループリーダー出ない場合は戻す.
            return redirect('users:login')

        return render(request, self.template_name, {
            "group": group,
            "members": group.members.all(),
            "unapproved_members": group.unapproved_members.all(),
            
        })

    def post(self, request, **kwargs):
        if 'action' in self.request.POST.keys():
            group_name = self.request.POST['group_name']
            member_email = self.request.POST['member_email']
            group = UserGroup.objects.get(name=group_name)
            target_user = User.objects.get(email=member_email)
            if self.request.POST['action'] == 'remove_member':
                group.members.remove(target_user)
            elif self.request.POST['action'] == 'approve':
                group.unapproved_members.remove(target_user)
                group.members.add(target_user)
            elif self.request.POST['action'] == 'remove_application':
                group.unapproved_members.remove(target_user)
            group.save()
        return redirect('users:manage_group', group_name=group_name)

templates/users/create_group.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
<div class="users__container">
    <img src="{% static 'common/images/logo_mini.png'%}" height="80px">
    <h1>Create Group</h1>
    <form action="" method="post">{% csrf_token %}
        {% if form.errors %}
            <div class="users__input">
                <div class="users__input__errors">
                    {% for errors in form.errors.values %}
                        {% for error in errors %}
                            {{ error }}<br>
                        {% endfor %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        {% for field in form %}
            <div class="users__input">
                {{ field }}
            </div>
        {% endfor %}
        <input type="number" name="leader_pk" value="{{ user.pk }}" hidden>
        <div class="users__input"><button class="users__submit" type="submit" name='action' value='create_group'>Create Group</button><br></div>
    </form>
</div>
{% endblock %}

templates/users/login.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <div class="users__container">
        <img src="{% static 'common/images/logo_mini.png'%}" height="80px">
        <h1>Login to CARM</h1>
            <form action="" method="post">{% csrf_token %}
                {% if form.errors %}
                    <div class="users__input">
                        <div class="users__input__errors">
                            {% for errors in form.errors.values %}
                                {% for error in errors %}
                                    {{ error }}<br>
                                {% endfor %}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                {% for field in form %}
                    <div class="users__input">
                        {{field.label}}<br>
                        {{ field }}<br><br><br><br>
                    </div>
                {% endfor %}
                <button class="users__submit" type="submit" name='action' value='login'>Login to CARM</button><br>
            </form>
            Do you have account ?&nbsp;<a href="{% url 'users:sign_up' %}">Sign up</a>
    </div>
{% endblock %}

templates/users/manage_and_search_group.html
{% extends 'common/base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'users/css/manage_and_search_group.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="users__container">
    <img src="{% static 'common/images/logo_mini.png'%}" height="80px">
    <h1>Manage・Search Group</h1>
    
    <h2>グループ検索</h2>
    <form action="" method="post">{% csrf_token %}
        <div class="search__group">
            <input class="search__input" type="text" name="searched_group_name" placeholder="group name">
            <button class="search__btn" type="submit" name='action' value='search_group'>検索</button><br>
            <input class="group__text" name="search_result" value="{% if searched_group_name is not None %}{{searched_group_name}}{% else %}該当グループなし{% endif %}" readonly><br>
            {% if member_status == "not_application" %}
                <button class="application__btn" type="submit" name='action' value='application'>参加申請</button>
            {% elif member_status == "unapproved" %}
                <button class="application__btn">参加申請済み</button>
            {% else %}
                <button class="application__btn">参加済み</button>
            {% endif %}
            
        </div>
    </form><br>

    <h2>所属グループ一覧</h2>
    {% for group in belong_groups %}
        <div class="belong__group__item">
            <form action="" method="post">{% csrf_token %}
                <input class="belong__group__item_text" name="group_name" value="{{group.name}}" readonly><br>
                {% if group == user.active_group %}
                    <button class="application__btn" type="button">アクティブ済み</button>
                {% else %}
                    <button class="application__btn" type="submit" name='action' value='activation'>アクティブ化</button>
                {% endif %}
                &nbsp
                {% if group.leader == user %}
                    <a href="{% url 'users:manage_group' group.name %}"><button class="application__btn" type="button">管理画面へ</button></a>
                {% else %}
                    <button class="application__btn" type="button">非管理者</button>
                {% endif %}
            </form>
        </div>
    {% endfor %}
</div>
{% endblock %}

{% block script %}
    <script src="{% static 'users/js/manage_and_search_group.js' %}"></script>
{% endblock %}

templates/users/manage_group.html
{% extends 'common/base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'users/css/manage_group.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="users__container">
    <h1>グループ：{{group.name}}</h1>
    <div class="members__container">
        <button type="button" class="narrow__btn member__item__trigger"  data-filter=".approved">承認済みonly</button>
        <button type="button" class="narrow__btn member__item__trigger"  data-filter=".application">未承認only</button>

        <form action="" method="post">{% csrf_token %}
            <div class="member_list">
                {% for member in members %}
                    {% if member != user %}
                        <input type="text" name="group_name" value="{{group.name}}" hidden>
                        <input type="text" name="member_email" value="{{member.email}}" hidden>
                        <div class="member__item mix filter approved">
                            <div class="member__item__text">{{member.username}}<br><span class="member__item__text__mini">{{member.email}}</span></div>
                            <button class="approve__btn" type="button">承認済み</button>
                            <button class="approve__btn" type="submit" name='action' value='remove_member'>削除</button>
                        </div>
                    {% endif %}
                {% endfor %}
                {% for member in unapproved_members %}
                    {% if member != user %}
                        <input type="text" name="group_name" value="{{group.name}}" hidden>
                        <input type="text" name="member_email" value="{{member.email}}" hidden>
                        <div class="member__item mix filter application">
                            <div class="member__item__text">{{member.username}}<br><span class="member__item__text__mini">{{member.email}}</span></div>
                            <button class="approve__btn" type="submit" name='action' value='approve'>承認</button>
                            <button class="approve__btn" type="submit" name='action' value='remove_application'>削除</button>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'users/js/manage_group.js' %}"></script>
{% endblock %}

templates/users/sign_up.html
{% extends 'common/base.html' %}
{% load static %}

{% block content %}
    <div class="users__container">
        <img src="{% static 'common/images/logo_mini.png'%}" height="80px">
        <h1>Sign up to CARM</h1>
        <form action="" method="post">{% csrf_token %}
            {% if form.errors %}
                <div class="users__input">
                    <div class="users__input__errors">
                        {% for errors in form.errors.values %}
                            {% for error in errors %}
                                {{ error }}<br>
                            {% endfor %}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            {% for field in form %}
                <div class="users__input">
                    {{ field }}
                </div>
            {% endfor %}
            <div class="users__input"><button class="users__submit" type="submit" name='action' value='sign_up'>Sign up to CARM</button><br></div>
        </form>
    </div>
{% endblock %}